name: Tests

on:
  push:
   branches:
     - master
  pull_request:
    branches:
     - "*"

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py_ver: ["3.7", "3.8"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.py_ver }}
    steps:
    - uses: actions/checkout@master
    - uses: conda-incubator/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.py_ver }}
        environment-file: environment.yaml
        activate-environment: sc
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info --all
        conda list
    - name: Running serial tests
      shell: bash -l {0}
      run: |
        pytest  tests \
                -vv \
                -n auto \
                --color=yes \
                --cov=./ \
                --cov-append \
                --cov-report html:coverage-html \
                --cov-report xml:coverage.xml \
                --cov-config=.coveragerc \
                --junit-xml=Linux-py${{ matrix.py_ver }}-serial.xml \
                --junit-prefix=Linux-py${{ matrix.py_ver }}-serial
